export const DEFAULT_PROPERTY_FALLBACK_IMAGE =
  'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80';

export const PROPERTY_CARD_FALLBACK_IMAGE = DEFAULT_PROPERTY_FALLBACK_IMAGE;
export const BOOKING_PROPERTY_FALLBACK_IMAGE = DEFAULT_PROPERTY_FALLBACK_IMAGE;
export const PUBLIC_PROFILE_FALLBACK_PROPERTY_IMAGE = DEFAULT_PROPERTY_FALLBACK_IMAGE;

export const SEARCH_PROPERTY_FALLBACK_IMAGE =
  'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80';
