import { PUBLIC_PROFILE_FALLBACK_PROPERTY_IMAGE as SHARED_PUBLIC_PROFILE_FALLBACK_PROPERTY_IMAGE } from '@/constants/propertyImages';

export const PUBLIC_PROFILE_FALLBACK_PROPERTY_IMAGE = SHARED_PUBLIC_PROFILE_FALLBACK_PROPERTY_IMAGE;
