import { AMENITY_CATEGORY_LABELS, LOCATION_TYPE_LABELS, PROPERTY_TYPE_OPTIONS } from '@/constants/propertyLabels';

export const COLLAPSIBLE_LIMIT = 6;

export const PROPERTY_TYPES = PROPERTY_TYPE_OPTIONS;

export const CATEGORY_LABELS = AMENITY_CATEGORY_LABELS;
export { LOCATION_TYPE_LABELS };
