export const ROUTES = {
  home: '/',
  search: '/search',
  searchMap: '/search/map',
  createProperty: '/properties/new',
  propertyDetailsPattern: '/properties/:id',
  propertyDetails: (id: number | string) => `/properties/${id}`,
  profile: '/profile',
  favorites: '/favorites',
  login: '/login',
  register: '/register',
  about: '/about',
  contacts: '/contacts',
  privacy: '/privacy',
  terms: '/terms',
} as const;
